import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import { SidebarProvider } from "@/components/SidebarContext";
import "@cloudscape-design/global-styles/index.css";
import "./globals.css";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Route 53 Clone",
  description: "Generated by Vaibhav Gupta",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${openSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans text-[14px] bg-[var(--color-background-layout-main)]">
        <SidebarProvider>
          {children}
        </SidebarProvider>
      </body>
    </html>
  );
}
